version: 2

aliases:
  - &workspace ~/deploy-directory-on-branch-to-gh-pages
  - &image circleci/node:lts

  - &container
    working_directory: *workspace
    docker:
      - image: *image

  - &attach-workspace
    attach-workspace:
      at: *workspace

  - &persist-workspace
    persist_to_workspace:
      root: .
      paths:
        - '*'

  - &install-dependencies
      name: Install dependencies
      command: yarn --frozen-lockfile

  - &lint
      name: Lint
      command: yarn lint

  - &check-changelog
      name: Check changelog and package.json version match
      command: yarn check-changelog

  - &run-tests
      name: Run tests
      command: yarn test

  - &set-up-npm-token
      name: Set up npm token
      command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc

  - &publish-to-npm
      name: Publish to npm
      command: yarn publish --access=public

  - &release-to-github
      name: Release to GitHub
      command: yarn release-to-github

jobs:
  install:
    <<: *container
    steps:
      - checkout
      - run: *install-dependencies
      - *persist-workspace

  lint:
    <<: *container
    steps:
      - *attach-workspace
      - run: *lint

  check-changelog:
    <<: *container
    steps:
      - *attach-workspace
      - run: *check-changelog

  test:
    <<: *container
    steps:
      - *attach-workspace
      - run: *run-tests

  publish:
    <<: *container
    steps:
      - *attach-workspace
      - run: *set-up-npm-token
      - run: *publish-to-npm

  release:
    <<: *container
    steps:
      - *attach-workspace
      - run: *release-to-github

workflows:
  version: 2
  workflow:
    jobs:
      - install

      - lint:
          requires:
            - install

      - check-changelog:
          requires:
            - install

      - test:
          requires:
            - install

      - release:
          requires:
            - test
            - check-changelog
            - lint
          filters:
            branches:
              only: master

      - publish:
          requires:
            - test
            - check-changelog
            - lint
          filters:
            branches:
              only: master
